web/router.ex
defmodule ElixirTraining.Router do
  use ElixirTraining.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  scope "/", ElixirTraining do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/login", LoginController, :login
    get "/countdown", CountdownController, :countdown
    get "/logout", LoginController, :logout
    post "/authenticate", LoginController, :authenticate

    post "/workout/create", TrainingController, :create

    get "/weight", WeightController, :index
    post "/weight/create", WeightController, :create

    get "/auth/callback", LoginController, :callback

    resources "/motivations", MotivationController
  end
end

web/views/layout_view.ex
defmodule ElixirTraining.LayoutView do
  use ElixirTraining.Web, :view

end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Kjersti's and Markus' *new* training challenge!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/login.css") %>">

  </head>

  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills">
          <%= if @authenticated do %>
            <li class="pill-right"><a href="<%= countdown_path @conn, :countdown %>">Countdown</a></li>
            <li class="pull-right"><a href="<%= login_path @conn, :logout %>">Logout</a></li>
          <%= else %>
            <li class="pull-right"><a href="<%= login_path @conn, :login %>">Login</a></li>
          <%= end %>

          <li class="pull-right"><a href="<%= page_path @conn, :index %>">Home</a></li>
        </ul>
      </div>

      <p class="alert alert-info"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Kjersti's and Markus' *new* training challenge!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/login.css") %>">
    
  </head>

  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills">
          <%= if @authenticated do %>
            <li class="pull-right"><a href="<%= login_path @conn, :logout %>">Logout <%= @current_user %></a></li>
          <%= else %>
            <li class="pull-right"><a href="<%= login_path @conn, :login %>">Login</a></li>
          <%= end %> 
          
          <li class="pull-right"><a href="<%= page_path @conn, :index %>">Home</a></li>
        </ul>
      </div>

      <p class="alert alert-info"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>