web/router.ex
defmodule ElixirTraining.Router do
  use ElixirTraining.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  scope "/", ElixirTraining do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/login", LoginController, :login
    get "/countdown", CountdownController, :countdown
    get "/logout", LoginController, :logout
    post "/authenticate", LoginController, :authenticate

    post "/workout/create", TrainingController, :create

    get "/weight", WeightController, :index
    post "/weight/create", WeightController, :create

    get "/auth/callback", LoginController, :callback

    resources "/motivations", MotivationController
  end
end

web/templates/page/add_training.html.eex
<form class="form-horizontal" action="<%= training_path(@conn, :create) %>" method="post">
  <input type="hidden" name="_csrf_token" value="<%= csrf_token %>">
  <label for="description" class="col-xs-3 control-label" style:"text-alignment:right">Description:</label>
  <div class="col-xs-9">
    <input type="input" class="form-control" id="description" name="description" />
  </div>
  <div class="col-xs-12" style="padding-top:5px; text-align:right">
    <button type="submit" class="btn btn-lg btn-success"> 
      <i class="glyphicon glyphicon-plus"></i> Add one training
      </button>
    </div> 
  </div>
</form>

web/templates/page/all_trainings.html.eex
<div class="row" style="margin-top:15px;">
  <div class="col-xs-12" style="text-align:center">         
    <div class="form-group">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Day</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <%= for training <- @trainings do %>
          <tr>  
            <td><%= training.inserted_at %></td>
            <td><%= training.description %></td>
          </tr>   
          <% end %>
        </tbody>
      </table>        
    </div>          
  </div>
</div>  
 

web/templates/page/index.html.eex
<div class="jumbotron">
  <h1>Kjersti's and Markus' *new* training challenge!</h1>
</div>

<div class="row">
  <div class="col-xs-5" style="text-align: right">
    <h2 class="<%= case ahead?(@participant1, @participant2) do
      true -> "text-success"
      _    -> "text-danger" end %>"><%= @participant1.name %></h2>
    <h1 class="big"><%= @participant1.current %></h1>
    <h3>(of <%= @participant1.goal %>)</h3>
    <blockquote class="blockquote-reverse">
      <p>"<%= @participant1.message %>"</p>
      <footer>William</footer>
    </blockquote>
  </div>

  <div class="col-xs-2" style="text-align: center">
    <h2>&nbsp;</h2>
    <h1 class="big">:</h1>
  </div>

  <div class="col-xs-5">
    <h2 class="<%= case ahead?(@participant2, @participant1) do
      true -> "text-success"
      _    -> "text-danger" end %>"><%= @participant2.name %></h2>
    <h1 class="big"><%= @participant2.current %></h1>
    <h3>(of <%= @participant2.goal %>)</h3>
    <blockquote>
      <p>"<%= @participant2.message %>"</p>
      <footer>William</footer>
    </blockquote>
  </div>

  <div class="col-xs-12">
    <%= if @authenticated do %>
      <%= render "weight_button.html", conn: @conn %>
      <%= render "add_training.html", conn: @conn %>
      <%= render "all_trainings.html", conn: @conn, trainings: @trainings %>
    <% end %>
  </div>
</div>

web/templates/page/training_button.html.eex
<div class="col-xs-12" style="text-align:center">
  <div class="form-group">
    <a href="<%= page_path(@conn, :index)%>" type="submit" class="btn btn-lg btn-success">
      <i class="glyphicon glyphicon-calendar"></i> Training
    </a>
  </div>
</div>

web/templates/page/weight_button.html.eex
<div class="row" style="margin-top:15px;">
  <div class="col-xs-12" style="text-align:center">         
    <div class="form-group">
      <a href="<%= weight_path(@conn, :index) %>" type="submit" class="btn btn-lg btn-success">
        <i class="glyphicon glyphicon-list"></i> Weight 
      </a>  
    </div>          
  </div>
</div>